---
spring:
  profiles: peer1
  application:
    name: eureka-client
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/


---
spring:
  profiles: peer2
  application:
    name: eureka-client
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/



