eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: eureka-client-one

management:
  security:
    enabled: false

logging:
  file: "logs/spring-cloud-eureka-client-one.log"



